services:
      
  db:
    image: postgres:16
    container_name: daylog-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h ${POSTGRES_HOST} -p ${POSTGRES_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data

  app:
    image: davidartifacts/daylog:${DAYLOG_VERSION}
    container_name: daylog-app
    ports:
      - 3000:3000
    environment:
      # See .env.example for all available environment variables
      - DATABASE_URL=${DATABASE_URL}
      - ENVIRONMENT=${ENVIRONMENT}
      - STORAGE_PATH=${STORAGE_PATH}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - storage:/app/storage

volumes:
  data:
  storage:
    driver: local

